
import "./globals.css";
import Header from "./_components/Header";

 // bricolage
 import { Bricolage_Grotesque } from "next/font/google";
 const  bricolage_grotesque= Bricolage_Grotesque({ subsets: ["latin"],
  weight: ['400', '700'], 
 });



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // set this className='dark' to enable dark mode 
    <html lang="en" className='dark'>
      <body className={bricolage_grotesque.className} >
        <Header/>
        {children}</body>
    </html>
  );
}
